### ISSUE TITLE
CustomerCreateRequest: incorrect return class ?

### ISSUE THREAD

**Issue by vancromp** [sphereio/sphere-php-sdk#109]
Hello,

I have noted a little problem when using the CustomerCreateRequest class.
The return class of CustomerCreateRequest is now Customer, but must be CustomerSigninResult to be in phase with response returned by api.

https://github.com/sphereio/sphere-php-sdk/blob/master/src/Request/Customers/CustomerCreateRequest.php#L21

Thanks for patch or explanation,
Have a good day :-)

Pierre

**Comment by ct-jensschulze** [comment]
Yeah you are right. Just hot fixed it. Thanks for reporting
