### ISSUE TITLE
Undefined index in ReferenceFromArrayTrait ?

### ISSUE THREAD

**Issue by vancromp** [sphereio/sphere-php-sdk#110]
Hello,

I get sometimes an undefined index notice (for index 'id') at this line :
https://github.com/sphereio/sphere-php-sdk/blob/master/src/Model/Common/ReferenceFromArrayTrait.php#L25

My quick and too dirty workaround is to return null when 'id' key doesn't exist.

Pierre

**Comment by ct-jensschulze** [comment]
In the develop branch this trait has been removed in favour of creating the reference from the document. 

E.g.:
```
$customer = CustomerFetchByIdRequest::ofId('<customer-id>')->executeWithClient($client);
$customerReference = $customer->getReference();
```

Can you give me a code snippet where try to create a reference directly?

**Comment by vancromp** [comment]
Ok, thanks :-) I will wait the merge of develop into master...

I don't use this method by myself, this was used internally by the sdk when doing some requests.
This was happened when i was trying to get customer group for a price (for a variant of masterdata of a product), that was assigned to "All" customer groups.
