### ISSUE TITLE
Inexistent fields in api response mapped to null values ?

### ISSUE THREAD

**Issue by vancromp** [sphereio/sphere-php-sdk#111]
Hello,

When I try to get, via sdk, a TaxedPrice from a cart that doesn't have already a TaxedPrice, i get a "empty" JsonObject that. After that, i try to get some fields of that empty JsonObject, and this raise some undefined index notice.

So, 2 questions : 
- How can i cleanly check that this JsonObject is empty before trying to get fields on it ?
- Maybe this JsonObject must be a null value to be more explicit ?

Thanks !

Pierre

**Comment by ct-jensschulze** [comment]
At the moment i don't have to proper solution how to identify and correctly return empty objects. But i just realized that it seems i have fixed this issue already in the develop branch and the move to named constructors.

**Comment by nkuehn** [comment]
@ct-jensschulze can you clarify what exactly is "fixed"?  Does the TaxedPrice (Magic) getter return null or an Object with no properties or throw an error? 

If it's yet to be decided I would vote vor doing it like a "plain" getter on a local Object variable would behave (probaly return null?)

**Comment by nkuehn** [comment]
@vancromp we will do this first:  #113  (return null reliably). 
For accessing deep object paths in a convenient matter we're playing with options, but that's outside the SDK scope.

**Comment by nkuehn** [comment]
Fixed with #113  by 8b138e7b56bc2339bb3f486235936627d1ea30f1

**Comment by vancromp** [comment]
Thanks :-)
