### ISSUE TITLE
Problem with set/get customer company name

### ISSUE THREAD

**Issue by vancromp** [sphereio/sphere-php-sdk#112]
Hello,

After trying to set the company name of a customer via the sdk, i don't see this previously set value when retrieving the customer. If I'm not wrong, I think this is a api-level problem.

Thanks !

**Comment by ct-jensschulze** [comment]
Could not reproduce the problem. My example code:

```
$request = CustomerFetchByIdRequest::ofId('8eb7de74-36d8-4796-8d30-9cc5ed47da63');
$response = $request->executeWithClient($client);
$customer = $request->mapResponse($response);

$request = CustomerUpdateRequest::ofIdAndVersion($customer->getId(), $customer->getVersion());
$request->addAction(CustomerSetCompanyNameAction::of()->setCompanyName('New Company'));

$response = $request->executeWithClient($client);
$customer = $request->mapResponse($response);
var_dump($customer->getCompanyName());
```

**Comment by vancromp** [comment]
Oh, ok, sorry, I was wrong about the use of CustomerSetCompanyNameAction :
the company name value is not a constructor parameter like some other actions.

Thanks for your response !

Pierre

**Comment by nkuehn** [comment]
P.S: @vancromp  You may want to read this section of the general API documentation: http://dev.sphere.io/http-api.html#partial-updates   Maybe you've heard of the "CQRS" pattern already.  You never just upload a complete new version of an Object in the SPHERE API, you rather post update commands to the platform that incrementally update the Object. Internally an update action is an event and you can poll some of the events at the "Messages" API endpoint (e.g. if you want to find out about Order status changes).
