### ISSUE TITLE
Add functional documentation text to PHP SDK specific public API methods 

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-php-sdk#16]
Goal:  
- being able to read through the generated API docs
- explaining atypical or domain specific stuff (e.g. no need to write text for "setName(string)" :-) )

Links to REST API reference manual would be helpful, too (don't duplicate too much text)

**Comment by ct-jensschulze** [comment]
Update (NK): because it looks like there will be structured documentation about the API models, endpoints, parameters and update actions e.g. RAML,  we should just document everything else for now and try to pull the rest in automatically.
