### ISSUE TITLE
Exception when running composer: guzzle

### ISSUE THREAD

**Issue by rzenner** [sphereio/sphere-php-sdk#84]
[RuntimeException]                                                           
  Could not load package guzzlehttp/guzzle in http://packagist.org: [Unexpect  
  edValueException] Could not parse version constraint ^1.1: Invalid version   
  string "^1.1"

**Comment by ct-jensschulze** [comment]
Can not reproduce. Could be a packagist hiccup

**Comment by kevinquillen** [comment]
Still happening for me.

**Comment by ct-jensschulze** [comment]
Could you give me more insights what exactly you are doing?

Just to use the php-sdk as a dependency in an empty project with

`composer require sphere/php-sdk dev-master`

And the second also cloned the repository and just ran

`composer install`

which also worked fine.

You could also add -vvv after the composer require/install and post the output

**Comment by ct-jensschulze** [comment]
And please use a `composer self-update` before. Just to make sure you have the latest composer version. :)

**Comment by nkuehn** [comment]
@kevinquillen do you still have the issue?

**Comment by nkuehn** [comment]
Closing due to lack of feedback and non-reproducibility
