### ISSUE TITLE
restrict retry on expired token on one try

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-php-sdk#96]
Context could have a flag  "autoRefreshToken", which is true by default, but the actual retry request is automatically set to false to be sure it does not run into an endless loop.

**Comment by nkuehn** [comment]
@ct-jensschulze  you mentioned that this is or may be done with a recent commit. Is that right?  Or just partially?

**Comment by ct-jensschulze** [comment]
Added link to the commit which resolves this issue
